In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Question 2: Create a Series and DataFrame using the data given in Table 2.14.

data1= {"Location":
 ['United States', 'India', 'Brazil', 'Russia', 'United Kingdom', 'France', 'Spain', 'Italy', 'Turkey', 'German'],
      "Cases":
       [ 28833039, 11079979, 10517232, 4246079, 4170519, 3736016, 3188553, 2907825, 2693164, 2444169],
    "Deaths":
      [517204, 156938, 254263, 86122, 122705,86332, 69142, 97507, 28503, 70601 ],
    "Recovered":
     [np.nan, 10763451, 9386440, 3811797, np.nan, np.nan, np.nan, 2398352, 2565723, 2242767]
      }


df1= pd.DataFrame(data1)

series_cases= pd.Series(df1["Cases"].values, index= df1["Location"], name= "Cases")
series_deaths= pd.Series(df1["Deaths"].values, index= df1["Location"], name= 'Deaths')
series_recovered= pd.Series(df1["Recovered"].values, index= df1["Location"], name= 'Recovered')

print(df1)
print(series_cases)
print(series_deaths)
print(series_recovered)

         Location     Cases  Deaths   Recovered
0   United States  28833039  517204         NaN
1           India  11079979  156938  10763451.0
2          Brazil  10517232  254263   9386440.0
3          Russia   4246079   86122   3811797.0
4  United Kingdom   4170519  122705         NaN
5          France   3736016   86332         NaN
6           Spain   3188553   69142         NaN
7           Italy   2907825   97507   2398352.0
8          Turkey   2693164   28503   2565723.0
9          German   2444169   70601   2242767.0
Location
United States     28833039
India             11079979
Brazil            10517232
Russia             4246079
United Kingdom     4170519
France             3736016
Spain              3188553
Italy              2907825
Turkey             2693164
German             2444169
Name: Cases, dtype: int64
Location
United States     517204
India             156938
Brazil            254263
Russia             86122
United Kingdom    122705
France             86332
Spain              69142
Italy              97507
Turkey             28503
German             70601
Name: Deaths, dtype: int64
Location
United States            NaN
India             10763451.0
Brazil             9386440.0
Russia             3811797.0
United Kingdom           NaN
France                   NaN
Spain                    NaN
Italy              2398352.0
Turkey             2565723.0
German             2242767.0
Name: Recovered, dtype: float64

In [ ]:
#Question 3: Create a new column (Status) in Qs 2 Dataframe. Analyze the “Cases” column, in case of less than 3 million cases set the Status to low. In case of greater than 3 million and less than 4 million cases Status is medium, otherwise high.

def status_col(cases):
  if cases < 30000000:
    return 'Low'
  elif 30000000 <= cases > 40000000:
    return 'Medium'
  else:
    return 'High'

df1["Status"]= df1['Cases'].apply(status_col)
df1

         Location     Cases  Deaths   Recovered Status
0   United States  28833039  517204         NaN    Low
1           India  11079979  156938  10763451.0    Low
2          Brazil  10517232  254263   9386440.0    Low
3          Russia   4246079   86122   3811797.0    Low
4  United Kingdom   4170519  122705         NaN    Low
5          France   3736016   86332         NaN    Low
6           Spain   3188553   69142         NaN    Low
7           Italy   2907825   97507   2398352.0    Low
8          Turkey   2693164   28503   2565723.0    Low
9          German   2444169   70601   2242767.0    Low

In [ ]:
#Question 4:Rank the created Series and DataFrame in ascending order of deaths count.

df1new= df1.fillna(0)
cases_rank= series_cases.rank()
death_rank= series_deaths.rank()
recovered_rank= series_recovered.rank()

df1new['Deaths_Rank']= df1['Deaths'].rank(method= 'max')
df1new

         Location     Cases  Deaths   Recovered Status  Deaths_Rank
0   United States  28833039  517204         0.0    Low         10.0
1           India  11079979  156938  10763451.0    Low          8.0
2          Brazil  10517232  254263   9386440.0    Low          9.0
3          Russia   4246079   86122   3811797.0    Low          4.0
4  United Kingdom   4170519  122705         0.0    Low          7.0
5          France   3736016   86332         0.0    Low          5.0
6           Spain   3188553   69142         0.0    Low          2.0
7           Italy   2907825   97507   2398352.0    Low          6.0
8          Turkey   2693164   28503   2565723.0    Low          1.0
9          German   2444169   70601   2242767.0    Low          3.0

In [ ]:
#Question 5: Compute the statistics of the created Series and DataFrame by using Table 2.10 functions.

answer1= df1.describe()
answer2= series_cases.describe()
answer3= series_deaths.describe()
answer4= series_recovered.describe()

print(answer1)
print(answer2)
print(answer3)
print(answer4)

              Cases         Deaths     Recovered
count  1.000000e+01      10.000000  6.000000e+00
mean   7.381658e+06  148931.700000  5.194755e+06
std    8.172197e+06  143366.103826  3.845493e+06
min    2.444169e+06   28503.000000  2.242767e+06
25%    2.978007e+06   74481.250000  2.440195e+06
50%    3.953268e+06   91919.500000  3.188760e+06
75%    8.949444e+06  148379.750000  7.992779e+06
max    2.883304e+07  517204.000000  1.076345e+07
count    1.000000e+01
mean     7.381658e+06
std      8.172197e+06
min      2.444169e+06
25%      2.978007e+06
50%      3.953268e+06
75%      8.949444e+06
max      2.883304e+07
Name: Cases, dtype: float64
count        10.000000
mean     148931.700000
std      143366.103826
min       28503.000000
25%       74481.250000
50%       91919.500000
75%      148379.750000
max      517204.000000
Name: Deaths, dtype: float64
count    6.000000e+00
mean     5.194755e+06
std      3.845493e+06
min      2.242767e+06
25%      2.440195e+06
50%      3.188760e+06
75%      7.992779e+06
max      1.076345e+07
Name: Recovered, dtype: float64

In [ ]:
#Question6: Fill the missing data of Table 2.14 with the mean and median value of a Series by using fillna function.
fill_mean= series_recovered.mean()
fill_median= series_recovered.median()

df1new1= df1.fillna(fill_mean)
df1new2= df1.fillna(fill_median)